# Generated by Django 5.1.5 on 2025-01-24 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowing',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
